sorties:
  - restaurant
  - cafe
  - brunch
  - spectacle
salaire:
  - optiver
abonnements:
  - youtube
  - amazon prime
credit:
  - credit maison
courses:
  - coles
  - grocery
  - aldi
  - harris farm
santé:
  - pharmacie
  - docteur
  - dentiste
achats:
  - amazon
divers:
  - poste
  - kmart
  - opal
  - divers
golf:
  - golf
voiture:
  - parking
enfant:
  - cc enfants
  - divers enfants
maison:
  - entretien
  - energie