categories:
  sorties:
    - restaurant
    - cafe
    - brunch
    - spectacle
  salaire:
    - optiver
  abonnements:
    - youtube
  credit:
    - maison
  courses:
    - coles
    - grocery
    - aldi
    - harris farm
  divers:
    - poste
  voiture:
    - parking
  enfant:
    - compte commun enfants
  maison:
    - entretien