sorties:
  - restaurant
  - cafe
  - brunch
  - spectacle
salaire:
  - optiver
abonnements:
  - youtube
  - amazon prime
credit:
  - credit maison
courses:
  - coles
  - grocery
  - aldi
  - harris farm
santé:
  - pharmacie
  - docteur
divers:
  - poste
  - amazon
  - kmart
voiture:
  - parking
enfant:
  - cc enfants
maison:
  - entretien